#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


echo '
===============================================================================
=| 🏗️👷 Styling , testing and building your project before committing...
===============================================================================
'

# Check Prettier standards
npm run check-format ||
(
npm run format && echo '
===============================================================================
=| 🤢🤮🤢🤮
=| Its FOKING RAW - Your styling looks disgusting.
=| (╯°□°）╯︵ ┻━┻
=| I have just formated code for you, now you have to try commit again.
=| Next time remember to run 🚩 npm run format 🚩 before commiting you code.
===============================================================================
';
false;
)

# Check ESLint Standards
npm run check-lint ||
(
echo '
===============================================================================
=| 😤🏀👋😤
=| Get that weak shit out of here!
=| (╯ಠ_ಠ)🔪🔪🔪🔪🔪🔪🔪
=| ESLint Check Failed.
=| Make the required changes listed above, then changes and try to commit again.
===============================================================================
'
false; 
)

# Check tsconfig standards
npm run check-types ||
(
echo '
===============================================================================
=| 🤡😂❌🤡
=| Failed Type check.
=| 🤡😂❌🤡
=| Are you seriously trying to write that?
=| Make the changes required above.
===============================================================================
'
false;
)

# If everything passes... Now we can commit
# echo '
# ===============================================================================
# =| 🤔🤔🤔🤔 Alright... Code looks good to me... Trying to build now. 
# ===============================================================================
# '
# 
# npm run build ||
# (
# echo '
# ===============================================================================
# =| ❌👷🔨❌
# =| Better call Hieu... Because your build failed
# =| ❌👷🔨❌
# =| Next build failed: View the errors above to see why. 
# ===============================================================================
# '
# false;
# )

# If everything passes... Now we can commit
echo '
===============================================================================
=| ✅✅✅✅ You win this time... I am committing this now. 🎉🎉🎉🎉
=| ~(￣▽￣)~*
===============================================================================
'